### PR TITLE
[draft] GHA: another attempt for dependencies (see #331)

### PR DESCRIPTION
**Pull request by vhotspur**

### CODE REVIEW

**Comment by lbulej** [comment]
Seems to be going the right way ;-) What will be used for the status icon on the Renaissance website? When the files were split, we used the "main" workflow, which reported only the result of building on LTS 17 on Linux/MacOS/Windows. From what will be derived the result of this workflow?

BTW, given how slow the builds are, consider building only on LTS version (8, 11, 17) + plus the most recent one (i.e. 18)?

**Comment by vhotspur** [comment]
@lbulej Can we merge this? I made in mistake in the last PR (#361) as the dependent workflows are actually always run on `master` and never actually touch the code of the branch in the PR.

Right now, it reports 20 minutes duration which is quite fine and it fails fast.

**Review by lbulej — APPROVED** [review]
> @lbulej Do you think we can merge this? I made in mistake in the last PR (#361) as the dependent workflows are actually always run on `master` and never actually touch the code of the branch in the PR. Thanks!

LGTM. Just keep an eye on the website button.

> >  BTW, given how slow the builds are, consider building only on LTS version (8, 11, 17) + plus the most recent one (i.e. 18)?
> Right now, it reports 20 minutes duration and it fails fast. Do we want to drop the other versions completely?

My point is, I'm not sure we would care too much if it failed anywhere between LTS versions and was fine with the LTS versions and the latest versions. So maybe it will not be faster, but we will waste less resources. It might be an interesting thing to do for releases (i.e. tags), but I don't find it of much value for normal development. Part of it may be that the (former) linux workflow with other JDKs has been failing so much recently (despite my attempts at restarting the builds), that I started to completely ignore it.

**Comment by vhotspur** [comment]
> > @lbulej Do you think we can merge this? I made in mistake in the last PR (#361) as the dependent workflows are actually always run on `master` and never actually touch the code of the branch in the PR. Thanks!
> 
> LGTM. Just keep an eye on the website button.

Will do.


> > > BTW, given how slow the builds are, consider building only on LTS version (8, 11, 17) + plus the most recent one (i.e. 18)?
> > > Right now, it reports 20 minutes duration and it fails fast. Do we want to drop the other versions completely?
> 
> My point is, I'm not sure we would care too much if it failed anywhere between LTS versions and was fine with the LTS versions and the latest versions. So maybe it will not be faster, but we will waste less resources. It might be an interesting thing to do for releases (i.e. tags), but I don't find it of much value for normal development. Part of it may be that the (former) linux workflow with other JDKs has been failing so much recently (despite my attempts at restarting the builds), that I started to completely ignore it.

That is a good point. I will merge this as it fixes the current state and will have a look at having the other jobs available for tags only.

**Pull request merged**
