### PR TITLE
CI: test on JDK17

### PR DESCRIPTION
**Pull request by vhotspur**
Follow-up to PR #297.

JDK17 for Mac and Windows is not yet available, tracked here: actions/setup-java#229

### CODE REVIEW

**Comment by lbulej** [comment]
> JDK17 for Mac and Windows is not yet available, tracked here: [actions/setup-java#229](https://github.com/actions/setup-java/issues/229)

By "not available", you mean just on GHA, right?

Given that JDK17 is available as a download, I'd like to see the 0.13 release running on Mac and Windows in addition to Linux. Do we wait for GHA to support it out of the box, or we try to install it ourselves now and simplify the CI after GHA starts supporting JDK17?

**Comment by vhotspur** [comment]
> > JDK17 for Mac and Windows is not yet available, tracked here: [actions/setup-java#229](https://github.com/actions/setup-java/issues/229)
> 
> By "not available", you mean just on GHA, right?

Yes.

> Given that JDK17 is available as a download, I'd like to see the 0.13 release running on Mac and Windows in addition to Linux. Do we wait for GHA to support it out of the box, or we try to install it ourselves now and simplify the CI after GHA starts supporting JDK17?

I would prefer to wait (I have nowhere to reasonably test it) but I guess we can use [this workaround](https://github.com/actions/setup-java/issues/229#issuecomment-919678258) if you need it for 0.13. I will have a look.

BTW, when you are in process of making a release, would you, please, add some kind of bullet list of things that needs to be done to the documentation branch (PR #294)?

**Comment by farquet** [comment]
I've manually tested on Mac and it works just fine. Linux is tested in the CI. So if someone can give it a shot on Windows just to be sure, I think we're safe for the release.

Regarding the CI, we can just keep this PR open until JDK17 is available on GHA for Mac and Windows. Or do a subsequent PR later on, but in any case, it shouldn't block the release. We have to take advantage of the JDK17 release momentum to do the renaissance release :)

**Comment by vhotspur** [comment]
Summary: testing with JDK17 on Mac, Windows and Linux, can be merged (the failed checks are spurious problems IMHO).

> I've manually tested on Mac and it works just fine. Linux is tested in the CI. So if someone can give it a shot on Windows just to be sure, I think we're safe for the release.

After figuring out how to use `aria2` adding Mac was relatively easy (I just had to fix `sed` portability issues (again)).

> Regarding the CI, we can just keep this PR open until JDK17 is available on GHA for Mac and Windows. Or do a subsequent PR later on, but in any case, it shouldn't block the release. We have to take advantage of the JDK17 release momentum to do the renaissance release :)

After release, we shall re-think how CI should work because this is becoming unmanageable (too many jobs, impossible to restart just one, always testing platforms that are not that interesting, running jobs twice for PRs etc.).

**Review by farquet — APPROVED** [review]

**Pull request merged**
