### PR TITLE
Update Spark to version 3.5.0

### LINKED ISSUE #370: NoSuchMethodException: java.nio.DirectByteBuffer.<init>(long,int) with newest JDK 21-b7
We are using 0.14.1.
Starting from JDK 21-b7, this exception happens related to the bug fix for  https://bugs.openjdk.org/browse/JDK-8299684

If this is fixed in Renaissance, possibly by a Spark upgrade, in newer unreleased code please let me know and we will plan for that.

java.lang.ExceptionInInitializerError
at org.apache.spark.unsafe.array.ByteArrayMethods.<clinit>(ByteArrayMethods.java:54)
at org.apache.spark.internal.config.package$.<clinit>(package.scala:1149)
at org.apache.spark.SparkConf$.<clinit>(SparkConf.scala:654)
at org.apache.spark.SparkConf.set(SparkConf.scala:94)
at org.apache.spark.SparkConf.set(SparkConf.scala:83)
at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$1(SparkSession.scala:920)
at scala.collection.mutable.HashMap$Node.foreach(HashMap.scala:627)
at scala.collection.mutable.HashMap.foreach(HashMap.scala:489)
at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:920)
at org.renaissance.apache.spark.SparkUtil.setUpSparkContext(SparkUtil.scala:121)
at org.renaissance.apache.spark.SparkUtil.setUpSparkContext$(SparkUtil.scala:92)
at org.renaissance.apache.spark.Als.setUpSparkContext(Als.scala:43)
at org.renaissance.apache.spark.Als.setUpBeforeAll(Als.scala:88)
at org.renaissance.jmh.JmhRenaissanceBenchmark.setUpBenchmark(JmhRenaissanceBenchmark.java:115)
at org.renaissance.apache.spark.jmh_generated.JmhAls_runOperation_jmhTest._jmh_tryInit_f_jmhals0_G(JmhAls_runOperation_jmhTest.java:590)
at org.renaissance.apache.spark.jmh_generated.JmhAls_runOperation_jmhTest.runOperation_SingleShotTime(JmhAls_runOperation_jmhTest.java:477)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:475)
at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:458)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.IllegalStateException: java.lang.NoSuchMethodException: java.nio.DirectByteBuffer.<init>(long,int)
at org.apache.spark.unsafe.Platform.<clinit>(Platform.java:113)
... 26 more
Caused by: java.lang.NoSuchMethodException: java.nio.DirectByteBuffer.<init>(long,int)
at java.base/java.lang.Class.getConstructor0(Class.java:3685)
at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2854)
at org.apache.spark.unsafe.Platform.<clinit>(Platform.java:71)
... 26 more

### PR DESCRIPTION
**Pull request by lbulej**
Updating Spark prompted an update of the logging configuration, so I took the opportunity to move logging configuration from benchmark utility code to the log4j2 configuration file.

More importantly though, updating Spark to version 3.5.0 resolves a compatibility problem with JDK21, i.e., it fixes #370.

### CODE REVIEW

**Review by vhotspur — APPROVED** [review]
Looks good.

**Comment by lbulej** [comment]
OK, there seems to be some trouble on Windows, so merging this will have to wait a bit until I find what "dependent libraries" are actually needed.

**Comment by lbulej** [comment]
I dropped the patches that bump Hadoop to version 3.3.5 (leaving it at 3.3.4 requested by Spark) and update the Windows binaries. The checks **do** pass with `hadoop.dll` and `winutils.exe` compiled from Hadoop 3.3.0 source, which I would consider an acceptable outcome (for this particular platform).

**Comment by caojoshua** [comment]
Thank you for this patch. Are there plans to have a release with this patch?

**Comment by lbulej** [comment]
> Thank you for this patch. Are there plans to have a release with this patch?

Yes, soonish &mdash; in a week or two I hope, so that we have a release in which most benchmarks (except a few) are compatible with JDK21.

**Pull request merged**
