### PR TITLE
Adding CI check for the standalone mode.

### PR DESCRIPTION
**Pull request by farquet**
It exhibits a problem with `dotty` which looks like a JDK compatibility issue:

```
====> dotty
Benchmark 'dotty' failed with exception:
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at org.renaissance.scala.dotty.Dotty.setUpBeforeAll(Dotty.scala:106)
	at org.renaissance.harness.ExecutionDriver.executeBenchmark(ExecutionDriver.java:82)
	at org.renaissance.harness.RenaissanceSuite$.$anonfun$runBenchmarks$1(RenaissanceSuite.scala:163)
	at org.renaissance.harness.RenaissanceSuite$.$anonfun$runBenchmarks$1$adapted(RenaissanceSuite.scala:159)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.renaissance.harness.RenaissanceSuite$.runBenchmarks(RenaissanceSuite.scala:159)
	at org.renaissance.harness.RenaissanceSuite$.main(RenaissanceSuite.scala:132)
	at org.renaissance.harness.RenaissanceSuite.main(RenaissanceSuite.scala)
The following benchmarks failed: dotty
```

### CODE REVIEW

**Comment by lbulej** [comment]
This is due to the fact that we build a class path for Dotty in the setup phase and while doing that, we assume that the class loader is the URLClassloader. It apparently isn't when the class path is defined in the manifest. Can you turn it into an issue?

Thanks for the CI check, LGTM.

**Comment by farquet** [comment]
- [ ] Rebase the branch once this is fixed -> #347

**Review by vhotspur — APPROVED** [review]
Apart from the Dotty issue the patch looks good. Thanks!

**Comment by farquet** [comment]
Rebasing on @lbulej 's PR, dotty isn't a problem anymore.

**Comment by farquet** [comment]
I spoke too fast. It seems that now it's OpenJ9 on JDK8 who still has issues with this mechanism:
```
====> dotty
Benchmark 'dotty' failed with exception:
java.lang.NullPointerException
	at org.renaissance.scala.dotty.Dotty.classPathFromManifest$1(Dotty.scala:162)
	at org.renaissance.scala.dotty.Dotty.buildDottyClassPath(Dotty.scala:182)
	at org.renaissance.scala.dotty.Dotty.setUpBeforeAll(Dotty.scala:106)
	at org.renaissance.harness.ExecutionDriver.executeBenchmark(ExecutionDriver.java:82)
	at org.renaissance.harness.RenaissanceSuite$.$anonfun$runBenchmarks$1(RenaissanceSuite.scala:163)
	at org.renaissance.harness.RenaissanceSuite$.$anonfun$runBenchmarks$1$adapted(RenaissanceSuite.scala:159)
	at org.renaissance.harness.RenaissanceSuite$$$Lambda$122/0x00000000f49f9350.apply(Unknown Source)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.renaissance.harness.RenaissanceSuite$.runBenchmarks(RenaissanceSuite.scala:159)
	at org.renaissance.harness.RenaissanceSuite$.main(RenaissanceSuite.scala:132)
	at org.renaissance.harness.RenaissanceSuite.main(RenaissanceSuite.scala)
The following benchmarks failed: dotty
```

**Comment by lbulej** [comment]
I noticed that too and tried to re-run the CI to see if it's fluke or not. I initially coded it with optionals to avoid null pointer exception when we fail to get a manifest input stream, but because that's something that should not really happen, I chose to let it fail if it happens so that we find out. But I did not expect to find out so quickly, because I don't see how that could fail: why, if you only have a single jar on the class path, could we not get manifest from the context class loader.

**Comment by farquet** [comment]
Since this problem is only affecting a specific vendor on an old java version (JDK8) and in a specific mode (standalone). It's probably not critical to fix it (unless the fix is obvious, but it doesn't look like it).
So I would suggest either to drop `openj9-openjdk8` from the linux matrix, or to drop the standalone test on linux (it would also be tested in the main, macos and windows pipelines.

Any thought on this ?

I think we shouldn't hold the 0.14 release because of that.

**Comment by lbulej** [comment]
> Since this problem is only affecting a specific vendor on an old java version (JDK8) and in a specific mode (standalone). It's probably not critical to fix it (unless the fix is obvious, but it doesn't look like it).

I have just downloaded OpenJ9 with JDK8, and it fails on my machine (but OpenJ9 with JDK11 does not) so I'll give it a quick look...

> So I would suggest either to drop openj9-openjdk8 from the linux matrix, or to drop the standalone test on linux (it would also be tested in the main, macos and windows pipelines.
> Any thought on this ?

It's what I would default to is no obvious fix.

> I think we shouldn't hold the 0.14 release because of that.

Agreed.

**Comment by lbulej** [comment]
It turns out I was just stupid, see #349

**Comment by ceresek** [comment]
Lucky we're talking past tense here :-)

**Comment by lbulej** [comment]
> Lucky we're talking past tense here :-)

The past tense only applies to that particular problem... I reserve the right to be stupid in future :-)

**Comment by lbulej** [comment]
One more rebase, for peace of mind.

**Pull request merged**
